<?php

return [
    "mandarin_title" => "Mandarin",
    "orange_title" => "Orange",
    "lemon_title" => "Lemon",
    "grapefruit_title" => "Grapefruit",

    "mandarin" => "Mandarin can be described as a type of citrus that has a reddish-orange color. Mandarins are sweeter in taste than oranges and have a sharper aroma. Mandarin, which is among the indispensable fruits of the winter months in our country, stands out with the high amount of vitamin C it contains. While Mandarin is harvested during the winter months, the most produced place is in the entire Mediterranean Region, especially Antalya. Mandarins, which have an important place in the export sector of our country, are a kind of citrus fruit that is widely used in the food industry. Mandarins, which have many positive effects in terms of health, also have a pleasant smell and taste. Mandarin has also become the champion of citrus exports in the first half of 2020. While an export of 228 thousand tons was realized, the financial equivalent of this export was approximately 125 million dollars.",

    "orange" => "Oranges, known for their positive effects on blood pressure regulation and heart health, have a wide production area in our country. Orange production is generally carried out in January, February and March. It is produced in the Aegean coasts, the Eastern Black Sea Region, the Southern Anatolia Region and the Mediterranean Region. The place where the highest production is made is Antalya. Oranges produced in our country are preferred in the international market due to their high quality and long durability. The highest quality orange production in our country takes place in Finike district of Antalya. In addition, oranges have an important place in citrus exports of our country. An export of around 92 thousand tons was realized in January - July 2020 period. The financial equivalent of this export is approximately 64 million dollars. At this point, it is seen that the value of 31 million dollars in the same period of the previous year nearly doubled.",

    "lemon" => "Although lemon is not preferred to be consumed directly, it is a kind of citrus fruit that enters our tables indirectly. It has a bitter, acidic and rather sour taste compared to orange and mandarin. One of the main reasons for consuming it is the sour taste it has. Thanks to the high amount of vitamin C it contains, it has a very important position to fight infections, especially in winter. Even if its homeland is India, it is actively produced in the Mediterranean region of our country. Especially in our provinces of Hatay and Mersin, lemons that are superior in terms of quality and quantity are produced. Lemon, which has an important place in terms of export, had an export share of 245 thousand tons in the first six months of 2019, while 150 thousand tons were exported in the same period of 2020. This export has a trade volume of approximately 92 million dollars. The main reason for this decline in exports is seen as the fact that suppliers do not turn to exports due to the difficulty of production to meet domestic needs.",

    "grapefruit" => "Grapefruits contain plenty of potassium, vitamin C and lycopene. Consuming grapefruit at ideal levels, which also has a blood pressure lowering effect, has positive effects on heart health. In addition, grapefruit is a citrus that is consumed as an antioxidant. Grapefruits, like other citrus fruits, are mostly produced in the Mediterranean Region. Adana is the city where the most grapefruit production is realized. Grapefruit; It is a type of citrus that is harvested in October, November, December, January and February. It is generally not consumed directly due to its bitter and acidic taste. However, it is a product that is used in many meals and throughout the food industry. grapefruit produced in Turkey, to their large size and long duration against adverse conditions is preferred because of its advantage to withstand. When we look at the data on grapefruit exports carried out by our country, we see that a sales of 115 thousand tons was realized in the first half of 2020. The foreign currency that this sale adds to the economy of our country is approximately 53 million dollars.",
];