<?php

return [
    "cherry" => "most of the cherries grown in Turkey between Izmir, Konya and Manisa are the first three, respectively. Cherry exports in the leading position in the world, in a position that performs the most export quality cherries cherry stands with Turkey. Cherry bigger, delicious and endurance while not having features that improve the quality of cherries such as Turkey have a long production of cherries, sees too much attention to respond to the demand in the national market. While approximately 70 thousand tons of cherries were exported in the first half of 2020, the financial equivalent of this export is approximately 190 million dollars. With these figures, it is the leader in the export of cherry exports, fresh fruits and vegetables.",

    "peach" => "Peach is a fruit that can grow in temperate climates. Locations of peach production is highest in Turkey, respectively, Aegean, Mediterranean, and Eastern and Western Marmara Sea of Marmara. In global markets, Turkey peaches, peach production capacity of 608 thousand tons 6. Next is located. a little behind the rest in peach production between Mediterranean countries, Turkey in fresh fruit and vegetable exports accounted 4th row of peach. Especially in June, July and peach production took place in August, the sector contribution to Turkey at the level of approximately $ 104 million. Peach, which is a sensitive fruit type that can be damaged quickly, is a fruit that can be stored between -0.5 and 0 degrees in full-fledged cold storage for 2 weeks to 4 weeks.",

    "apple" => "Apple is a fruit rich in antioxidants and dietary fiber. Ranking 7th in our country's fruit and vegetable exports, apple reached a trade volume of approximately 65 million lira in the January - July 2020 period. While the apple trees are mostly located in Karaman, the champion of apple production is our city, Isparta. On the other hand, while Karaman takes the second place, Niğde takes the third place. While approximately 124 thousand tons of apples were exported in the January - July period of 2020, this figure was 179 thousand tons in the same period of 2019. However, despite the significant export amount, the apples exported in 2020 earned 10 million dollars more.",

    "pomegranate" => "Pomegranate, which is generally sour but also has sweet types, is a fruit that is used frequently in appetizers and snacks. Pomegranate grown in Turkey, especially in the city of Denizli, is a very durable product. Pomegranate, which can keep up even in arid environments, is a fruit resistant up to -10 degrees. In addition, it has many positive contributions to the human body such as strengthening the immune system. Ranking 9th in the export ranking of our country, pomegranate has a trade volume of approximately 54 million dollars. Our country's pomegranate export is increasing rapidly thanks to the support of the studies and the farmer's choices. For example, while 81 thousand tons of exports were realized between January and July 2019, this figure increased to 99 thousand tons in the same period of 2020.",

    "strawberry" => "Strawberry is a fruit that grows in spring and is actively used in many food industries. When we look at it, it is used in many foods from cakes to jams. It is able to withstand long periods of strawberry produced in Turkey, who pretty much in demand because of the color and taste of a strawberry being preferred. Turkey in an amount close to each other in 2019 and 2020 (approximately 25 thousand tons) export strawberries. strawberry ice cream that are being exported from Turkey generally is used to ensure that the demands made in the food sector, such as cakes and biscuits. On the other hand, when we look at the export volumes, we see that most strawberries are exported to Russia. Russia exported 13 thousand was realized, up nearly 50% of the strawberries were exported from Turkey.",

    "apricot" => "It is known for its positive effects on digestive health apricots, one made of fruit exported to Turkey. apricots, which are grown in most Malatya in Turkey, as a berry that grows in the summer emerges. Its durability and longevity is one of the main factors contributing to its export. While Germany is the place where most exports are made, apricots are exported to 10 different countries in total, including Hong Kong and Singapore, which are among the Far Eastern countries. Apricot Turkey's exports of fruits and vegetables, a fruit, which is located 10 Values. The trade volume of apricots, which was exported approximately 23 thousand tons in the first half of 2020, reaches up to 24 million dollars.",

    "plum" => "It grows almost everywhere except in the arid and extremely hot places in the Southeastern Anatolia Region and the high regions of the Eastern Anatolia Region known as the plateau. We can say that it is the fruit with the greatest difference in quality from product to product between fruits and vegetables. Therefore, plums are carefully separated during and after harvesting. The weight of plums produced in Turkey, Russia, Azerbaijan and are exported to some Arab countries. Erik, 30 thousand tons of export volume and $ 24 million with exports of fruit and vegetables in Turkey ranking age brings with it the amount exported is located 15 Values. Various plums such as Life Plum, Freeze, Priest, Damson, Anjelica can be found in the market.",
    
    "grape" => "It is possible to grow grapes almost everywhere in our country. But not all grapes can be grown in all regions. The grape types that need to be grown differ according to the region. Many varieties of grapes such as Yalova Pearl, Merlot Grape, Hamburg Muscat Grape, Syrup are available in the market. One of the fruits and vegetables that our country exports to is grape. Approximately 85% of the grapes produced in Manisa, where the most grapes are grown in our country, are exported, while 15% are exported to the domestic markets. When we look at Turkey's overall export data for January 2020 - between July, 21 thousand tons realized an export, the total trade volume of these exports around 17 million dollars. However, these rates increase due to the increase in production in the second half of the year.",

    "sour_cherry" => "Sour Cherry, which has physical properties similar to sour cherry, is a fruit that is used in different areas than sour cherry. While cherries can be used in the food industry and for table, sour cherry is a fruit that is not generally used for table consumption. Sour cherries are generally used in the food industry such as jam making, fruit juice and snacks. The reason for this can be interpreted as having a sour taste. Looking at the first cherry production in Turkey, while Afyonkarahisar, Kütahya is coming from behind. While cherry production is made intensely in July-August, it is found in regions where production is delayed to autumn. sour cherries being produced in Turkey are exported to approximately 95 countries. When we look at the increase in this export rate in recent years, we can predict that exports will continue to increase.",

    "pear" => "Containing plenty of fiber in its skin, pear is also a very good source of vitamin C. The pears are produced in Turkey, due to the very high quality products in terms of taste, the most preferred product in the international market. The pears produced are exported to approximately 53 countries, although it changes every year. Issuance of countries from Russia and Iraq, a ratio of about 60% of Turkey's most exported by the two countries pears position. In the first quarter of 2020, approximately 17 thousand tons of pear was exported. When we look at the commercial value of exports, we see a value of around 12 million. Pear ranks 19th in our country's fresh fruit and vegetable export ranking.",
    
    "cherry_title" => "Cherry",
    "peach_title" => "Peach",
    "apple_title" => "Apple",
    "pomegranate_title" => "Pomegranate",
    "strawberry_title" => "Strawberry",
    "apricot_title" => "Apricot",
    "plum_title" => "Plum",
    "grape_title" => "Grape",
    "sour_cherry_title" => "Sour Cherry",
    "pear_title" => "Pear", 

];