<?php

return [
    "tomato_title" => "Tomato",
    "pepper_title" => "Pepper",
    "pumpkins_title" => "Pumpkins",
    "cucumber_title" => "Cucumber",
    "eggplant_title" => "Eggplant",
    "onion_title" => "Onion",
    "carrot_title" => "Carrot",
    "radish_title" => "Radish",
    "potato_title" => "Potato",
    "broccoli_title" => "Broccoli",

    "tomato" => "When tomatoes are considered in terms of weight, they rank first in the list of products exported by our country. In the first half of 2020, approximately 294 thousand tons of tomatoes were exported by our country. Although it is very close to the same period of the previous year, it has increased by around 4%, when we look in terms of export values, we see that there is a larger trade volume in 2020. Tomatoes, which are grown especially in summer, are also produced in winter months in environments such as greenhouses in order to meet the needs of the country and to meet the international demand for tomatoes. Tomatoes produced in our country are exported to many European and non-European countries, especially Russia.",

    "pepper" => "The highest pepper production in our country takes place in June, July, August and September. Peppers are one of the leading products among the most indispensable vegetables and fruits in our kitchens. In addition to vitamin C, peppers are also a product that has an appetite enhancing effect. Peppers grown in our country are one of the most preferred peppers in the international market because they are very strong in terms of quality and durability. Peppers can be added to main meals or can be used in a variety of snacks. When we look at the pepper export data in our country, we see that pepper has a serious export of 97 thousand tons. The figure resulting from this export consists of 101 million Turkish Liras.",

    "pumpkins" => "Pumpkins are vegetables that are used in many different areas in the food industry. It has a long growing period in June, July, August and September. Pumpkin is virtually resistant against various climates vegetables can be grown in all regions of Turkey, but is one of the highlights of training in Sakarya. Pumpkins planned to be exported are preferred to be durable for a long time. In the period of January - July 2020, around 45 thousand tons of squash were exported. The income from this export is approximately 32 million dollars. According to the data, the country where Turkish pumpkins are exported most is Russia, which constitutes a large part of our total exports.",

    "cucumber" => "Cucumber is a vegetable that is consumed both directly for table purposes and is needed in the food industry. Cucumber, known for its high productivity, shows higher performance in heat. Therefore, we can call it a heat-loving vegetable, and it is also a suitable vegetable for greenhouse cultivation. Size, color, taste has very different from each other as a kind and vegetables that can be grown almost anywhere in Turkey. Cucumbers, which started to be harvested in May, continue to produce throughout the summer. When we look at the cucumber export data of our country, we see that an export of 27 thousand tons was realized in the first 6 months of 2020. The financial equivalent of this export is approximately 22 million dollars.",

    "eggplant" => "Our country; Together with states such as China, India, Egypt and Italy, it is among the countries with the highest eggplant production in the world. It is the only living people who eat eggplant found in nature, and this is thought to be because it contains a little nicotine. We look forward to eggplant production in Turkey if the cities are as follows; Antalya, Sanliurfa and Hatay. Due to the high demand in these provinces, eggplant production is at higher levels. Eggplant, which is produced from June to September, can be grown almost everywhere in our country thanks to its ability to adapt to many climates. When we look at the eggplant export dimension of our country, we encounter serious figures. In the period of January - July 2020, around 20 thousand tons of eggplant were exported.",

    "onion" => "One of the indispensable products of the food industry is onion. Onions are vegetables that grow under the ground and have only their leaves above the ground. Production continues from April to September and even from time to time until October. Onions, which can adapt to many climatic conditions, are more productive and grow better in hot seasons. Also, even if onions are not in season, they are very easily found vegetables everywhere. When we take a look at the onion export data in our country, there is a great increase. In the January-July period of 2019, 37 thousand tons of exports were made, and when we look at the same period of 2020, we see a figure of 53 thousand tons. When we look at the trade volumes, unfortunately, we cannot see the same increase, 2019 and 2020 are very close to each other, around 10 million dollars.",

    "carrot" => "Although it is a vegetable with different varieties such as purple, red, black, yellow and white, it is a vegetable that is generally known for its orange form. It is a root vegetable, just like onion and potatoes. Carrot, which has vitamins such as A, C and K and has many benefits for the human body, is a vegetable that is actively used in many areas. Konya is the place where carrots are mostly grown in our country. Approximately 50% of Turkey's total production takes place in Konya carrots. The amount of carrots imported from Turkey, approximately 39 thousand tons in the first 6 months of the year and the volume of this trade around $ 6 million. Turkey carrots resistance, excels in terms of taste, color and hearty.",

    "radish" => "Radish is a long rooted vegetable with two different forms, round or cylindrical. It is a root vegetable like carrots and onions. In general, its cylindrical form is consumed in the food industry and its round form is consumed for table purposes. It is a very rich vegetable in terms of vitamin C, potassium and folic acid. In addition, we can say that it is a very healthy vegetable for radish, which contains plenty of vitamins B2 and B6. Radish production, which started in November in our country, continues throughout the winter months and even in March in some regions. radishes produced in Turkey are quite durable and highly preferred is a product abroad because it is delicious.",

    "potato" => "Potato appears as a vegetable that is consumed in almost every region of the world. Potatoes, which are everywhere in the food industry, are a vegetable with a very high level of consumption, especially for direct table consumption. Potato cultivation is mostly seen in the Central Anatolia Region in our country. While the most production takes place in Nevşehir; Potato production is also at very high levels in Konya, Niğde, Erzurum, Sakarya, Trabzon and İzmir. Planted in February and March, potatoes are also harvested in summer. Because it is a durable vegetable, it is a product that can be found every month of the year. When we look at Turkey's potato export data for the first half of 2020 it appears to have an export of 29 thousand tons. The value of this export is approximately 4 million dollars.",

    "broccoli" => "The homeland of broccoli is known as the Mediterranean. In our country, broccoli is mostly grown in the Mediterranean region. It is clear when we look at Turkey's broccoli production data is increasing every year. If this increase continues, it is estimated that broccoli will become an important product in fresh fruit and vegetable exports. Broccoli, which has many positive effects on the human body such as strengthening the digestive system, protecting heart health and regulating blood sugar, is an important alternative for people who want to eat healthy. broccoli produced in Turkey are preferred because of high quality in many markets. The production is due to Turkey's top exporting countries where climatic conditions broccoli performs known as Ukraine is almost zero.",


];