<?php

return [
    "mandarin_title" => "Mandalina",
    "orange_title" => "Portakal",
    "lemon_title" => "Limon",
    "grapefruit_title" => "Greyfurt",

    "mandarin" => "Mandarin, kırmızımsı – turuncu bir renge sahip olan bir çeşit turunçgil olarak tanımlanabilir. Mandarinlerin tadı, portakallara göre daha tatlıdır ve daha keskin bir aromaya sahiptir. Ülkemizde özellikle kış aylarının vazgeçilmez meyveleri arasında yer alan mandarin, içerisinde bulundurduğu yüksek miktarda C vitamini ile öne çıkmaktadır. Mandarin, kış ayları içerisinde hasat edilirken, en çok üretimin yapıldığı yer özellikle Antalya olmak üzere tüm Akdeniz Bölgesidir. Ülkemizin ihracat sektöründe de önemli bir yeri olan mandarinler, gıda endüstrisinde oldukça fazla kullanılmakta olan bir narenciye çeşididir. Sağlık açısından birçok olumlu etkisi bulunan mandarinler aynı zamanda hoş bir kokuya ve tada sahiptir. Mandarin aynı zamanda 2020 yılının ilk yarısında narenciye ihracatının da şampiyonu olmuştur. 228 bin tonluk bir ihracat gerçekleşirken, bu ihracatın maddi karşılığı da yaklaşık olarak 125 milyon dolar olmuştur.",

    "orange" => "Kan basıncını düzenlemesi ve kalp sağlığı üzerindeki olumlu etkileri ile bilinmekte olan portakallar, ülkemizde geniş bir üretim alanına sahiptir. Portakal üretimi genellikle ocak, şubat ve mart aylarında gerçekleştirilmektedir. Ege kıyılarında, Doğu Karadeniz Bölgesinde, Güney Anadolu Bölgesinde ve Akdeniz Bölgesinde üretimi gerçekleşmektedir. En yüksek üretimin yapıldığı yer ise Antalya ilidir. Ülkemizde üretilen portakallar yüksek kalitesi ve uzun süre dayanabilmesi gibi özellikleri sayesinde uluslararası pazarda tercih edilmekte olan bir üründür. Ülkemizin en kaliteli portakal üretimi ise Antalya ilimizin Finike ilçesinde gerçekleşmektedir. Ayrıca portakallar ülkemizin narenciye ihracatında da önemli bir yere sahiptir. 2020 ocak – temmuz döneminde 92 bin ton civarı bir ihraç gerçekleştirilmiştir. Gerçekleştirilen bu ihracın maddi karşılığı ise yaklaşık olarak 64 milyon dolardır. Bu noktada önceki yılın aynı döneminde 31 milyon dolar olan değerin yaklaşık iki katına çıktığı görülmektedir.",

    "lemon" => "Limon, doğrudan tüketilmesi pek tercih edilmeyen bir ürün olsa da sofralarımıza dolaylı yoldan girmekte olan bir narenciye çeşididir. Portakal ve mandarinle kıyaslandığında daha acı, asidik ve oldukça ekşi bir tada sahiptir. Zaten tüketilmesinin ana sebeplerinden birisi de sahip olduğu ekşi tattır. İçerisinde barındırdığı yüksek miktarda C vitamini sayesinde özellikle kış aylarında enfeksiyonlarla mücadele etmek için oldukça önemli bir konuma sahiptir. Anavatanı Hindistan olsa bile ülkemizin Akdeniz bölgesinde aktif bir şekilde üretimi gerçekleştirilmektedir. Özellikle Hatay ve Mersin illerimizde nitelik ve nicelik bakımından oldukça üstün limonlar üretilmektedir. İhracat bakımından da önemli bir yere sahip olan limon, 2019 yılının ilk altı ayında 245 bin tonluk bir ihraç payına sahipken, 2020 yılının aynı döneminde 150 bin ton ihraç edilmiştir. Bu ihraç yaklaşık olarak 92 milyon dolarlık bir ticaret hacmine sahiptir. İhracatta yaşanan bu düşüşün ana sebebi ise üretimin iç ihtiyaçları karşılamakta zorlanması nedeniyle tedarikçilerin ihraca yönelmemesi olarak görülmektedir.",

    "grapefruit" => "Greyfurtlar içerisinde bol miktarda potasyum, C vitamini ve likopen barındırmaktadır. Kan basıncını düşürücü etkisi de bulunan greyfurtun ideal düzeylerde tüketilmesi, kalp sağlığına olumlu etkilerde bulunuyor. Ayrıca greyfurt, antioksidan olarak da tüketilmekte olan bir narenciyedir. Greyfurtlar da diğer narenciyeler gibi çoğunlukla Akdeniz Bölgesinde üretilmektedir. En çok greyfurt üretiminin gerçekleştirildiği şehir ise Adana’dır. Greyfurt; ekim, kasım, aralık, ocak ve şubat aylarında hasat edilmekte olan bir narenciye türüdür. Acımsı ve asidik bir tadının olmasından dolayı genelde doğrudan tüketilmemektedir. Fakat birçok yemek içerisinde ve gıda sektörünün genelinde kullanılmakta olan bir üründür. Türkiye’de üretilen greyfurtlar, boyutlarının büyük olması ve olumsuz koşullara karşı uzun süreler dayanabilmesi gibi avantajlarından dolayı tercih edilmektedir. Ülkemiz tarafından gerçekleştirilen greyfurt ihracatındaki verilere baktığımız zaman, 2020 yılının ilk yarısında 115 bin tonluk bir satışın gerçekleştiğini görüyoruz. Bu satışın, ülkemizin ekonomisine kattığı döviz ise yaklaşık olarak 53 milyon dolar.",
];