<?php

return [
    "cherry" => "Türkiye’de en fazla kirazın yetiştiği bölgeler arasında İzmir, Konya ve Manisa sırasıyla ilk üçü oluşturuyor. Kiraz ihracatı konusunda dünyada lider konumda, en çok kiraz ihracatını gerçekleştiren konumda olan Türkiye’nin kirazları kaliteleriyle öne çıkıyor. Kirazların daha iri, lezzetli olması ve dayanma süresinin uzun olması gibi kirazları daha kaliteli hale getiren özelliklere sahip olan Türkiye üretimi kirazlar, ulusal piyasada talebe karşılık veremeyecek kadar fazla ilgi görüyor. 2020 yılının ilk yarısında yaklaşık olarak 70 bin ton kiraz ihraç edilirken, bu ihracın maddi karşılığı da yaklaşık olarak 190 milyon dolar. Bu rakamlarla kiraz ihracatı, yaş meyve ve sebze ihracatı sektörünün lideri konumunda yer alıyor.",

    "peach" => "Şeftali, ılıman iklimlerde yetişebilen bir meyvedir. Türkiye’de şeftali üretiminin en yüksek olduğu yerler sırasıyla Ege, Akdeniz, Doğu Marmara ve Batı Marmara’dır. Global şeftali piyasasında ise Türkiye, 608 bin tonluk şeftali üretim kapasitesi 6. Sırada yer alıyor. Akdeniz ülkeleri arasında şeftali üretiminde biraz geride kalan Türkiye’de yaş meyve ve sebze ihracatında 4. sırayı şeftali oluşturuyor. Özellikle haziran, temmuz ve ağustos ayları içerisinde üretimi gerçekleşen şeftalinin, sektörde Türkiye’ye katkısı yaklaşık 104 milyon dolar seviyelerinde. Çabuk hasar alabilen, hassas bir meyve türü olan şeftali, tam teşekküllü soğuk hava depoları içerisinde, -0.5 ile 0 derece arasında, 2 haftadan 4 haftaya kadar muhafaza edilebilmekte olan bir meyvedir.",

    "apple" => "Elma antioksidan ve diyet lifi açısından oldukça zengin bir meyvedir. Ülkemizin meyve ve sebze ihracatında, 7. Sırada yer alan elma, 2020 ocak – temmuz döneminde yaklaşık olarak 65 milyon liralık bir ticaret hacmine ulaştı. En çok elma ağacı Karaman’da yer alırken, elma üretimi şampiyonu şehrimiz Isparta olarak karşımıza çıkıyor. Öte yandan, ikinci sırayı Karaman alırken, üçüncü sırada ise Niğde yer alıyor. 2020 ocak – temmuz döneminde yaklaşık 124 bin ton elma ihraç edilirken, bu rakam 2019 yılının aynı döneminde 179 bin tondu. Fakat bu aradaki ciddi ihraç miktarına rağmen 2020 yılında ihraç edilen elmalar 10 milyon dolar daha fazla para kazandırdı.",

    "pomegranate" => "Genellikle ekşi olan fakat tatlı türleri de bulunan nar, meze ve aperatifler de çok sık kullanılmakta olan bir meyvedir. Türkiye’de özellikle Denizli şehrinde yetiştirilen nar, çok dayanıklı bir üründür. Kurak ortamlara bile ayak uydurabilen nar, -10 dereceye kadar dirençli bir meyvedir. Ayrıca bağışıklık sistemini güçlendirmek gibi insan vücuduna birçok olumlu katkısı vardır. Ülkemizin ihracat sıralamasında 9. sırada yer alan nar, yaklaşık olarak 54 milyon dolarlık bir ticaret hacmine sahip. Ülkemizin nar ihracatı yapılan çalışmaların desteği ve çiftçinin seçimleri sayesinde hızlı bir artış gösteriyor. Örneğin, 2019 ocak – temmuz aralığında 81 bin ton ihracat gerçekleşirken 2020 yılının aynı döneminde bu rakam 99 bin tona kadar yükseliş gösterdi.",

    "strawberry" => "Çilek, ilkbahar mevsiminde yetişmekte olan, birçok gıda sektöründe aktif olarak kullanılan bir meyvedir. Baktığımız zaman çilek pastalardan tutunda reçellere kadar birçok gıdada kullanılıyor. Türkiye’de üretilmekte olan çileklerin uzun süre dayanabilmesi, renk ve tadından dolayı oldukça fazla rağbet gören, tercih edilmekte olan bir çilek. Türkiye 2019 ve 2020 yıllarında birbirine yakın miktarda (yaklaşık olarak 25 bin ton) çilek ihracatı gerçekleştirdi. Türkiye’den ihraç edilmekte olan çilekler genellikle dondurma, pasta ve bisküvi gibi gıda sektörlerinde oluşan talepleri sağlamak için kullanılıyor. Öte yandan ihraç miktarlarına baktığımızda en çok Rusya’ya çilek ihraç edildiğini görüyoruz. 13 bin ihracın gerçekleştiği Rusya, neredeyse Türkiye’den ihraç edilen çileklerin %50’sini oluşturuyor.",

    "apricot" => "Sindirim sağlığına olumlu etkileri ile bilinen kayısı, Türkiye’de ihracı yapılan meyvelerden birisi. Türkiye’de en çok Malatya bölgesinde yetiştirilmekte olan kayısı, yaz mevsimlerinde yetişen bir meyve olarak karşımıza çıkıyor. Dayanıklı ve uzun ömürlü olması, ihracına büyük bir katkı sağlayan faktörlerin başında geliyor. En çok ihracatın yapıldığı yer Almanya olurken, Uzak Doğu ülkelerinden olan Hong Kong, Singapur’da dahil olmak üzere toplamda 10 farklı ülkeye kayısı ihracatı gerçekleşiyor. Kayısı Türkiye’nin meyve ve sebze ihracatında 10. Sırada yer almakta olan bir meyve. 2020’nin ilk yarısında yaklaşık olarak 23 bin ton ihracı gerçekleştirilen kayısının ticaret hacmi ise 24 milyon dolara kadar ulaşıyor.",

    "plum" => "Güneydoğu Anadolu Bölgesinde yer alan kurak ve aşırı sıcak olan yerler ile yayla olarak bilinen Doğu Anadolu Bölgesinin yüksek mıntıkalı yerleri hariç neredeyse her yerde yetişmektedir. Meyve ve sebzeler arasında üründen ürüne değişen kalite farkının en çok olduğu meyvedir diyebiliriz. Bu yüzden erikler toplanma esnasında ve sonrasında dikkatli bir şekilde ayrıştırılmaktadır. Türkiye’de üretilen erikler ağırlıkla Rusya, Azerbaycan ve bazı Arap ülkelerine ihraç edilmektedir. Erik, 30 bin tonluk ihraç miktarı ve bu ihraç miktarının getirisi olan 24 milyon dolar ile Türkiye yaş meyve ve sebze ihracat sıralamasında 15. Sırada yer almaktadır. Can eriği, Freze, Papaz, Mürdüm, Anjelica gibi çeşitli erikler piyasalarda bulunabilmektedir.",

    "grape" => "Ülkemizin neredeyse her yerinde üzüm yetiştirmek mümkün. Fakat her üzüm her bölgede yetiştirilemiyor. Bulunulan bölgeye göre yetiştirilmesi gereken üzüm türleri farklılık gösteriyor. Yalova incisi, Merlot Üzümü, Hamburg Misketi Üzümü, Frengi Üzümü, gibi çok sayıda çeşit üzüm piyasada bulunabiliyor. Ülkemizin ihracatını gerçekleştirdiği meyve ve sebzelerden birisi de üzüm olarak karşımıza çıkıyor. Ülkemizde en çok üzüm yetiştirilen Manisa’da üretilen üzümlerin yaklaşık olarak %85’i ihraç edilirken, %15’i ise iç piyasalara sürülüyor. Türkiye’nin genel ihracat verilerine baktığımızda ise 2020 yılı Ocak – Temmuz arasında, 21 bin tonluk bir ihracat gerçekleşirken, bu ihracatın toplam ticaret hacmi ise 17 milyon dolar civarında. Fakat bu oranlar, yılın ikinci yarısında üretimin artmasına bağlı olarak artış gösteriyor.",

    "sour_cherry" => "Kiraza benzer fiziksel özelliklere sahip olan vişne, kiraza göre daha farklı alanlarda kullanılmakta olan bir meyve. Kiraz gıda endüstrisinde ve sofralık olarak kullanılabilirken, vişne genelde sofralık olarak kullanılmayan bir meyve. Vişne, genelde reçel yapımı, meyve suyu, aperatifler gibi gıda endüstrisi alanında kullanılıyor. Bunun sebebi ekşimsi bir tada sahip olması olarak yorumlanabilir. Türkiye’de vişne üretimine baktığımızda ilk sırada Afyonkarahisar yer alırken, arkasından Kütahya geliyor. Vişne üretimi yoğunlukla Temmuz- Ağustos aylarında yapılırken, üretimin sonbahar aylarına sarktığı bölgelerde bulunuyor. Türkiye’de üretilmekte olan vişneler yaklaşık olarak 95 ülkeye ihraç ediliyor. Bu ihracat oranının son yıllarda ki artışına baktığımızda, ihracatın artmaya devam edeceği tahmininde bulunabiliriz.",

    "pear" => "Kabuğunda bol miktarda lif barındıran armut, aynı zamanda çok iyi bir C vitamini kaynağıdır. Türkiye’de üretilen armutlar, tat bakımından oldukça kaliteli ürünler olması sebebiyle, uluslararası piyasada çok tercih edilen bir ürün. Üretilen armutlar, her sene değişmekle birlikte yaklaşık olarak 53 ülkeye ihraç ediliyor. İhraç edilen ülkeler arasından Rusya ve Irak, yaklaşık %60’lık bir oranla, Türkiye’nin en fazla armut ihraç ettiği iki ülke konumunda bulunuyor. 2020 yılının ilk çeyreğinde yaklaşık olarak 17 bin tonluk bir armut ihracatı gerçekleşti. İhracatın ticari değerine baktığımızda ise 12 milyon civarında bir değer karşımıza çıkıyor. Armut, ülkemizin yaş meyve ve sebze ihracat sıralamasında 19. Sırada yer alıyor.",
    
    "cherry_title" => "Kiraz",
    "peach_title" => "Şeftali",
    "apple_title" => "Elma",
    "pomegranate_title" => "Nar",
    "strawberry_title" => "Çilek",
    "apricot_title" => "Kayısı",
    "plum_title" => "Erik",
    "grape_title" => "Üzüm",
    "sour_cherry_title" => "Vişne",
    "pear_title" => "Armut",
];