<?php

return [

    "tomato_title" => "Domates",
    "pepper_title" => "Biber",
    "pumpkins_title" => "Kabak",
    "cucumber_title" => "Hıyar",
    "eggplant_title" => "Patlıcan",
    "onion_title" => "Soğan",
    "carrot_title" => "Havuç",
    "radish_title" => "Turp",
    "potato_title" => "Patates",
    "broccoli_title" => "Brokoli",

    "tomato" => "Domatesler ağırlık bakımından bakıldığı zaman ülkemiz tarafından ihracatı gerçekleştirilen ürünler listesinde birinci sırayı almaktadır. 2020 yılı ilk yarısı içerisinde yaklaşık olarak 294 bin ton domates ihracatı ülkemiz tarafından gerçekleştirildi. Bir önceki yılın aynı dönemine çok yakın olmakla beraber %4 civarında artış gösterirken, ihracat değerleri açısından baktığımızda ise 2020 yılında daha büyük bir ticaret hacmine sahip olunduğunu görüyoruz. Özellikle yaz aylarında yetişmekte olan domates, hem ülke ihtiyaçlarına cevap verilmesini sağlamak hem de uluslararası bazda duyulan domates ihtiyacının karşılanabilmesi adına sera gibi ortamlarda, kış ayları içerisinde de üretilmektedir. Ülkemizde üretilmekte olan domatesler Rusya başta olmak üzere birçok Avrupa ve Avrupa dışı ülkeye ihraç edilmektedir.",

    "pepper" => "Haziran, Temmuz, Ağustos ve Eylül aylarında ülkemizde ki en yükse biber üretimleri gerçekleşmektedir. Biberler, mutfaklarımızda bulunan, en vazgeçilmez konumda olan sebze ve meyveler arasından başı çeken ürünlerden bir tanesidir. Biberler C vitamininin yanı sıra, iştah arttırıcı etkisi de bulunan bir üründür. Ülkemizde yetiştirilmekte olan biberler kalite ve dayanıklılık gibi etkenler bakımından oldukça güçlü olduğu için uluslararası markette en çok tercih edilen biberlerden birisidir. Biberler ana yemeklerin içine katılabileceği gibi birçok aperatifte de çeşitli formlarla yer alabilmektedir. Ülkemizde biber ihracat verilerine baktığımızda biberin, 97 bin tonluk ciddi bir ihracata sahip olduğunu görüyoruz. Bu ihracat sonucu ortaya çıkan rakam ise 101 milyon Türk Lirasından oluşmaktadır.",

    "pumpkins" => "Kabaklar, gıda endüstrisi içerisinde birçok farklı alanda kullanılmakta olan sebzelerdir. Haziran, Temmuz, Ağustos ve Eylül olmak üzere uzun bir yetişme dönemine sahiptir. Kabak çeşitli iklim koşullarına karşı dayanıklı bir sebze olduğu neredeyse Türkiye’nin her bölgesinde yetiştirilebilmektedir fakat Sakarya yetiştirme konusunda öne çıkan bölgelerden birisidir. İhraç edilmesi planlanan kabakların uzun süre dayanıklı olmaları tercih edilmektedir. 2020 ocak – temmuz dönemi içerisinde 45 bin ton civarında kabak ihracatı gerçekleştirildi. Bu ihracattan elde edilen gelir ise yaklaşık olarak 32 milyon dolar olarak karşımıza çıkıyor. Türk kabaklarının en çok ihraç edildiği ülke ise verilere göre, toplam ihracatımızın büyük bir kısmını oluşturan Rusya olarak gözüküyor.",

    "cucumber" => "Hıyar hem doğrudan sofralık amaçlarla tüketilen hem de gıda endüstrisi içinde ihtiyaç duyulmakta olan bir sebzedir. Yüksek verimliliğe sahip olmasıyla bilinen salatalık, sıcaklarda daha yüksek performans göstermektedir. Bu yüzden sıcağı seven bir sebze diyebiliriz, ayrıca sera yetiştiriciliği yapılması içinde uygun bir sebzedir. Boyut, renk, tat gibi birbirinden çok değişik çeşitlere sahiptir ve neredeyse Türkiye’nin her yerinde yetiştirilebilen bir sebzedir. Mayıs ayında ürün alınmaya başlanan hıyarlar, tüm yaz boyunca ürün vermeye devam ederler. Ülkemizin hıyar ihracatı verilerine baktığımızda ise 2020 yılının ilk 6 ayında 27 bin tonluk bir ihracat gerçekleştiğini görüyoruz. Bu ihracatın maddi karşılığı ise yaklaşık 22 milyon dolar.",

    "eggplant" => "Ülkemiz; Çin, Hindistan, Mısır ve İtalya gibi devletlerle birlikte dünyada en çok patlıcan üretiminin gerçekleştirildiği ülkeler arasında yer alıyor. Doğada bulunan patlıcanı tek yiyen canlı insanlardır, bunun nedeni ise bünyesinde az da olsa nikotin barındırması olarak tahmin ediliyor. Türkiye’de patlıcan üretimlerine baktığımızda öne çıkan şehirler ise şöyle; Antalya, Şanlıurfa ve Hatay. Bu illerde talebinde fazla olması sebebiyle patlıcan üretimi daha yüksek seviyelerde. Haziran ayından Eylül ayına kadar üretimine devam edilen patlıcan, birçok iklime ayak uydurabilmesi sayesinde neredeyse ülkemizin her yerinde yetişebiliyor. Ülkemizin patlıcan ihracatı boyutuna baktığımızda ise ciddi rakamlarla karşılaşıyoruz. 2020 ocak – temmuz döneminde 20 bin ton civarı patlıcan, ihraç edilmiş.",

    "onion" => "Gıda endüstrisinin vazgeçilmez ürünlerden birisi de soğandır. Soğanlar, toprak altında yetişen, toprağın üstünde sadece yapraklarını bulunduran sebzelerdir. Nisan ayından eylül ayına kadar, hatta zaman zaman ekim ayına kadar üretimi sürmektedir. Birçok iklim koşuluna adapte olabilen soğanlar, sıcak mevsimlerde daha verimli olmakta ve daha iyi yetişmektedir. Ayrıyeten soğanlar mevsimi olmasa bile, her yerde çok rahat bulunabilen sebzelerdir. Ülkemizde soğan ihracatı verilerine göz attığımızda ise bir hayli yükseliş mevcut. 2019 yılı ocak – temmuz döneminde 37 bin ton ihracat gerçekleşmiş, 2020 yılı aynı dönemine baktığımızda ise 53 bin ton gibi bir rakamla karşılaşıyoruz. Ticaret hacimlerine baktığımızda ise maalesef aynı yükselişi göremiyoruz, 2019 yılı ile 2020 yılı birbirine çok yakın olarak, 10 milyon dolar civarında.",

    "carrot" => "Mor, kırmızı, siyah, sarı ve beyaz olmak üzere farklı çeşitlere sahip bir sebze olmasına rağmen genellikle turuncu renkli hali ile bilinmekte olan bir sebzedir. Tıpkı soğan ve patates gibi bir kök sebzedir. A, C ve K gibi vitaminlere sahip, insan vücuduna birçok faydası bulunan havuç, birçok alanda aktif şekilde kullanılmakta olan bir sebzedir. Ülkemizde havucun en çok yetiştirildiği yer ise Konya’dır. Türkiye’nin toplam havuç üretiminin yaklaşık olarak %50’si Konya’da gerçekleşiyor. Türkiye’den ithal edilen havuç miktarı, yılın ilk 6 ayında yaklaşık 39 bin ton ve bu ticaretin hacmi ise 6 milyon dolar civarında. Türkiye havuçları dayanıklılık, lezzet ve doyurucu renk bakımından öne çıkmakta.",

    "radish" => "Turp yuvarlak ya da silindirik olmak üzere iki farklı forma sahip, uzun köklü bir sebzedir. Havuç ve soğan gibi bir kök sebzedir. Genel olarak baktığımızda, silindirik formu gıda endüstrisinde, yuvarlak formu ise sofralık amaçlarla tüketilmektedir. C vitamini, potasyum ve folik asit açısından oldukça zengin bir sebzedir. Ayrıca B2 ve B6 vitaminlerini de bolca barındıran turp için gayet sağlıklı bir sebze olduğunu söyleyebiliriz. Ülkemizde Kasım ayı içerisinde başlayan turp üretimi, tüm kış ayları boyunca devam etmekte hatta bazı bölgelerde mart ayında dahi devam etmektedir. Türkiye’de üretilen turplar oldukça dayanıklı ve lezzetli olduğu için yurt dışında oldukça fazla tercih edilmekte olan bir ürün.",

    "potato" => "Patates dünyanın neredeyse her bölgesinde tüketilmekte olan bir sebze olarak karşımıza çıkıyor. Gıda endüstrisinin her yerinde yer alan patatesler, özellikle doğrudan sofralık amaçlı tüketimi çok yüksek seviyede olan bir sebzedir. Patates tarımı ülkemizde en fazla İç Anadolu Bölgesinde görülmektedir. En fazla üretim Nevşehir’de gerçekleşirken; Konya, Niğde, Erzurum, Sakarya, Trabzon ve İzmir’de de patates üretimi oldukça yüksek seviyelerdedir. Şubat ve mart aylarında dikimi gerçekleştirilen patates, yaz aylarında da hasat edilmektedir. Dayanıklı bir sebze türü olması nedeniyle yılın her ayı rahatlıkla bulunabilen bir üründür. Türkiye’nin patates ihracat verilerine baktığımızda ise, 2020 yılının ilk yarısında 29 bin tonluk bir ihracatın gerçekleştiği görülüyor. Bu ihracatın değeri ise yaklaşık 4 milyon dolar.",

    "broccoli" => "Brokolinin anavatanı Akdeniz olarak bilinmektedir. Ülkemizde de brokolinin en çok yetiştirildiği bölge, Akdeniz bölgesidir. Türkiye’nin brokoli üretim verilerine baktığımızda açıkça görülüyor ki her sene daha da artmaktadır. Bu artışın devam ettiği takdirde, yaş meyve ve sebze ihracatında brokolinin önemli bir ürün haline geleceği tahmin ediliyor. Sindirim sistemini güçlendirmek, kalp sağlığını korumak ve kan şekerini düzenlemesi gibi insan vücuduna birçok olumlu etkisi bulunan brokoli, sağlıklı beslenmek isteyen insanlar için önemli bir alternatif olarak karşımıza çıkıyor. Türkiye’de üretilen brokoliler yüksek kaliteleri sebebiyle birçok pazarda tercih edilmektedir. Türkiye’nin en çok brokoli ihracatını gerçekleştirdiği ülke ise iklim koşullarından dolayı üretimin neredeyse sıfır olduğu Ukrayna olarak biliniyor.",


];